languageCode = "zh-CN"
hasCJKLanguage = true
title = "AntiGameZ's Blog"
author = "Sijie (Alex) Chen"
theme = "hugo-pacman-theme"
RSSUri = "feed.xml"

[Params]
    twitter = "antigamez"
    github = "antigamez"
    linkIn = "sijiec"

[Params.Disqus]
    ShortName = "antigamezs"
