languageCode = "zh-CN"
hasCJKLanguage = true
title = "AntiGameZ's Blog"
author = "Sijie (Alex) Chen"
theme = "hugo-pacman-theme"
RSSUri = "feed.xml"
baseurl = "https://www.linrk.com/"
pygmentsStyle = "default"
pygmentsUseClasses = true

[Params]
    twitter = "antigamez"
    github = "antigamez"
    linkIn = "sijiec"
    FancyBox = true
    DateFormat = "2006年01月02日"
    MonthFormat = "2006年01月"

[Params.Disqus]
    ShortName = "antigamezs"
    
[Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"
