baseurl = "https://github.com/AntiGameZ/LinrkBlog"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "AntiGameZ's Blog"
author = "Sijie (Alex) Chen"
RSSUri = "feed.xml"
canonifyurls: true

[Params]
    twitter = "antigamez"
    github = "antigamez"
    linkIn = "sijiec"

[Params.Disqus]
    ShortName = "antigamezs"
